spring:
  application:
    name: Spring-blog-demo
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/spring_blog?characterEncoding=utf8&useSSL=false
    username: root
    password: Kevin@Qiu666
    driver-class-name: com.mysql.cj.jdbc.Driver